%% $Id$
Vars = case file:consult(filename:join([filename:dirname(SCRIPT), "..", "vars.config"])) of
    {ok, Terms} ->
        Terms;
    _Err ->
        []
    end,

Env = case lists:keyfind(enabled_backends, 1, Vars) of
    false ->
        {env, []};
    Backends ->
        {env, [Backends]}
    end,

{application, ejabberd,
 [{description, "ejabberd"},
  lists:keyfind(vsn, 1, Vars),
  {modules, []},
  {registered, []},
  {applications, [kernel, stdlib, sasl, ssl]},
  {included_applications,
    [os_mon,
     jiffy,
     lager,
     mnesia,
     mqtree,
     inets,
     yconf,
     pkix,
     xmpp,
     cache_tab,
     eimp,
     p1_acme,
     p1_oauth2]},
  Env,
  {mod, {ejabberd_app, []}}]}.


%% Local Variables:
%% mode: erlang
%% End:
%% vim: set filetype=erlang tabstop=8:
